#!/bin/sh

DIR="/home/kristo/.books/"
DEFAULT_READER=zathura

add_book() {
    BOOK=$1
    NAME=$2
    LIST=$3
    
    if ! [ -e "$BOOK" ]; then
        echo "Incorrect path. Book doesn't exist!"
        return -1
    fi

    if [ -e "$DIR$NAME" ]; then
        echo "Linkbook already exist!"
        return -1
    fi

    if [ -n "$LIST" ]; then
        read -p "List doesn't exist, do you want to create it? " ans
        if [ $ans = 'y' ] || [ $ans = '' ]; then
            $LIST = ""
            ln $BOOK "$DIR$NAME"
            echo "Link isn't created, link established!"
        else
            mkdir "$DIR$LIST"
            ln $BOOK "$DIR$LIST/$NAME"
            echo "List created, link established!"
        fi
    else
        echo $2
        ln "$BOOK" "$DIR$NAME"
        echo "Link established!"
    fi
}

remove_book() {
    NAME=$1
    LIST=$2

    if ! [ -e "$DIR$NAME" ]; then
        echo "Linkbook doesn't exist!"
    else
        read -p "Are you sure? " ans
        if [ $ans = 'y' ] || [ $ans = '' ]; then
            rm "$DIR$NAME"
        else
            break
        fi
    fi
}

list_books() {
    LIST=$1
    if [ -n $LIST ]; then
        ls $DIR$LIST
    else
        ls $DIR
    fi
}

open_book() {
    NAME=$1
    if [ -n "$2" ]; then
        LIST="$2/"
    else
        LIST=""
    fi

    echo $DIR$LIST$NAME
    if [ -e "$DIR$LIST$NAME" ]; then
        $DEFAULT_READER "$DIR$LIST$NAME"
    else
        echo "Linkbook doesn't exist"
    fi
}

case $1 in
    "add")
        add_book "$2" $3 
        ;;
    "rm")
        remove_book "$2"
        ;;
    "ls")
        list_books $2
        ;;
    "read")
        open_book "$2"
        ;;
    *)
        echo "Invalid arguments"
esac
