#!/bin/sh

DIR="/home/kristo/.books/"
DEFAULT_READER=sioyek

add_list() {
    LIST=$1
    if [ -e "$DIR$LIST" ]; then
        echo "List already exist!"
    else
        mkdir "$DIR$LIST"
    fi
}

add_book() {
    BOOK=$1
    NAME=$2
    LIST=$3
    if ! [ -e "$BOOK" ]; then
        echo "Incorrect path. Book doesn't exist!"
        return -1
    fi

    if [ -e "$DIR$LIST$NAME" ]; then
        echo "Linkbook already exist!"
        return -1
    fi
    
    if [ -z "$LIST" ]; then
        ln "$BOOK" "$DIR$NAME"
        echo "Link created!"
    elif
        [ -d "$DIR$LIST" ]; then
        ln "$BOOK" "$DIR$LIST/$NAME"
    else
        read -p "Do you want to create this list? " ans
        if [ "$ans" = "y" ] || [ "$ans" = "" ]; then
            mkdir "$DIR$LIST"
            ln "$BOOK" "$DIR$LIST/$NAME"
        else
            "OK... Nothing is done."
        fi
    fi
}

remove_book() {
    NAME=$1
    LIST=$2

    if ! [ -e "$DIR$NAME" ]; then
        echo "Linkbook doesn't exist!"
    else
        read -p "Are you sure? " ans
        if [ $ans = 'y' ] || [ $ans = '' ]; then
            rm "$DIR$NAME"
        else
            break
        fi
    fi
}

list_books() {
    LIST=$1
    if [ -n $LIST ]; then
        ls $DIR$LIST
    else
        ls $DIR
    fi
}

open_book() {
    NAME=$1
    LIST=$2
    if [ -n "$2" ]; then
        LIST="$2/"
    else
        LIST=""
    fi

    if [ -e "$DIR$LIST$NAME" ]; then
        $DEFAULT_READER "$DIR$LIST$NAME" > /dev/null &
    else
        echo "Linkbook doesn't exist"
    fi
}

move_book() {
    NAME=$1
    LIST=$2
    TO=$3
    if [ -e "$DIR$LIST/$NAME" ] && [ -d "$DIR$TO" ]; then
        mv "$DIR$LIST/$NAME" "$DIR$TO/$NAME"
    else
        echo "Link doesn't exist"
    fi
}

case $1 in
    "add")
        LIST=$(echo $3 | awk -F: '{print $1}')
        NAME=$(echo $3 | awk -F: '{print $2}')
        if [ -z "$NAME" ]; then
            NAME=$LIST
            LIST=""
        fi
        add_book "$2" "$NAME" "$LIST"
        ;;
    "rm")
        remove_book "$2"
        ;;
    "ls")
        list_books $2
        ;;
    "read")
        LIST=$(echo $2 | awk -F: '{print $1}')
        NAME=$(echo $2 | awk -F: '{print $2}')
        if [ -z "$NAME" ]; then
            NAME=$LIST
            LIST=""
        fi

        open_book "$NAME" "$LIST"
        ;;
    "move")
        LIST=$(echo $2 | awk -F: '{print $1}')
        NAME=$(echo $2 | awk -F: '{print $2}')
        if [ -z "$NAME" ]; then
            NAME=$LIST
            LIST=""
        fi
        move_book "$NAME" "$LIST" $3
        ;;
    "make")
        add_list $2
        ;;
    *)
        echo "Invalid arguments"
esac
